### ISSUE TITLE
Invalid JSON repository.json

### ISSUE THREAD

**Issue by csteele-PD** [tomwpublic/hpm#1]
Your JSON is "broken" and I can't see where anyone's mentioned it. 

In each 'package' you have a tag, but there's an extra comma.

"tags": [
        "Lights & Switches"
      ],
    },

The comma after the square bracket is indicating there's another key:value pair, and of course, there isn't. Each of your packages needs to be:

"tags": [
        "Lights & Switches"
      ]    <-- no comma
    },

**Comment by tomwpublic** [comment]
Fixed here: https://github.com/tomwpublic/hpm/commit/7c951f6dc7e534a9a24be66164e15a310f46e7e8

Thanks for reporting the issue!
